### PR TITLE
[#310] Add mozilla-django-oidc-db

### LINKED ISSUE #310: ADFS-integration is not working in v1.1.0
It appears that ADFS-integration is broken in v1.1.0. When logging in through ADFS, the following traceback is being served:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django_auth_adfs/views.py", line 85, in get
    return redirect(provider_config.build_authorization_endpoint(request))
  File "/usr/local/lib/python3.8/site-packages/django_auth_adfs/config.py", line 329, in build_authorization_endpoint
    self.load_config()
  File "/usr/local/lib/python3.8/site-packages/django_auth_adfs/config.py", line 208, in load_config
    loaded = self._load_openid_config()
  File "/usr/local/lib/python3.8/site-packages/django_auth_adfs/config.py", line 234, in _load_openid_config
    if settings.VERSION != 'v1.0':

Exception Type: AttributeError at /adfs/login
Exception Value: 'Settings' object has no attribute 'VERSION'
```

In v1.1.0 the `django-auth-adfs` has been [bumped](https://github.com/maykinmedia/archiefbeheercomponent/commit/116e8dea0c0555e0e41090436daf11170b27d4ea#diff-0940fec0afe21798f617cc4522db676f15769ae28a72992b8d19216ef7b1c3b5R58) from `1.6.1` to `1.10.0`. 
It appears that somewhere down the line the `VERSION` attribute in the default `Settings` class [was introduced ](https://github.com/snok/django-auth-adfs/commit/2b8fef7f38151a9698dd9bc031714b84298c05a3#diff-45e27f33f5764512f60c4c826bb199f1f4f16639f8db4f29b288ada6d6df82cbR77) and became mandatory. 

For ArchiefBeheerComponent `django_auth_adfs_db.settings.Settings` is being used as Settings_Class and that [does not contain](https://github.com/isprojects/_obsolete_django-auth-adfs-db/blob/main/django_auth_adfs_db/settings.py#L42) a `VERSION` attribute. 

This can be confirmed through a Django shell:
```
>>> from django_auth_adfs_db.settings import *
>>> dir(Settings)
['AUDIENCE', 'BOOLEAN_CLAIM_MAPPING', 'CA_BUNDLE', 'CLAIM_MAPPING', 'CLIENT_ID', 'CLIENT_SECRET', 'CONFIG_RELOAD_INTERVAL', 'CREATE_NEW_USERS', 'CUSTOM_FAILED_RESPONSE_VIEW', 'DISABLE_SSO', 'GROUPS_CLAIM', 'GROUP_TO_FLAG_MAPPING', 'JWT_LEEWAY', 'LOGIN_EXEMPT_URLS', 'MIRROR_GROUPS', 'RELYING_PARTY_ID', 'RETRIES', 'SERVER', 'TENANT_ID', 'TIMEOUT', 'USERNAME_CLAIM', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
```

I guess moving towards the new OIDC-plugin (as used within the new Open-Zaak release) would be the proper way forward, or would downgrading `django-auth-adfs` back to 1.6.1 be feasible as a fix on the short-term?

### PR DESCRIPTION
**Pull request by SilviaAmAm**
Fixes #310

### CODE REVIEW

**Review by sergei-maertens — APPROVED** [review]
I'd also include the automated migration from adfs -> oidc - you can look at open-zaak for this. Otherwise, the next version would be a breaking change.
